name: Setup
runs:
  using: composite
  steps:
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy
    - uses: Swatinem/rust-cache@v1
    - name: Install spellchecker
      run: |
        npm install -g spellchecker node-gyp
        echo "NODE_PATH=$(npm config get prefix)/lib/node_modules" >> $GITHUB_ENV
      shell: bash
    # - name: Install Depot
    #   run: curl https://raw.githubusercontent.com/cognitive-engineering-lab/depot/main/scripts/install.sh | sh
    #   shell: bash
    - name: Install Depot
      run: cargo install --git https://github.com/cognitive-engineering-lab/depot depot-js --locked --debug && depot setup      
      shell: bash
    # Note: we have to build before test so the build script is executed
    - name: Build Rust package
      run: cargo build
      shell: bash
    - name: Test Rust package
      run: cargo test      
      shell: bash
    - name: Lint Rust package
      run: cargo clippy -- -D warnings      
      shell: bash
    - name: Test JS package
      run: depot test
      working-directory: js
      shell: bash