name: Tests

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - "**"

env:
  AQUASCOPE_VERSION: 0.3.1

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/workflows/setup
      - name: Install Aquascope
        run: |
          curl -sSL https://github.com/cognitive-engineering-lab/aquascope/releases/download/v${AQUASCOPE_VERSION}/aquascope-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
          echo "$(pwd)/bin" >> ${GITHUB_PATH}
      - name: Test Rust package
        run: cargo test --all-features --locked
      - name: Lint Rust package
        run: cargo clippy --all-features --locked -- -D warnings
      - name: Test JS package
        run: depot test
        working-directory: js