name: Tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - run: npm install -g pnpm
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
      # Build script in previous action should build js,
      # so we don't need to run pnpm build here.
      - run: pnpm test && pnpm lint
        working-directory: js
      - run: cargo install --path . --debug --locked
      - run: mdbook build
        working-directory: example
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/book
            
